### ISSUE TITLE
Support relative sizes for maps

### ISSUE THREAD

**Issue by rick-de-water** [majorimi/blazor-components#130]
`Width` and `Height` are defined in pixels, and there is no way to set a map to a relative value such as a percentage. This makes dynamically filling part of the screen with the map very difficult.

**Comment by rick-de-water** [comment]
I work around the issue for now by putting the map in a div and adding the following css:
```css
.map-container > div {
    width: 100% !important;
    height: 100% !important;
}
```
